# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: docker-image:tag
image: voidso/bb-build:latest
pipelines:
  default:
    - step:
        script:
          - mkdir build && cd build
          - cmake ../
          - make
          - cd ../ && rm -rf build && mkdir build && cd build
          - cmake ../ -DNM_DEBUG=ON -DNM_SAVEVM_SNAPSHOTS=ON -DNM_WITH_NETWORK_MAP=ON
          - make
